name: Golang General

on:
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: "1.19"

permissions:
  contents: write

jobs:
  code_qualtity:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '1'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go_version }}
          cache: false
        
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          install-mode: "binary"


  testing:

    runs-on: ubuntu-latest
    needs: [ code_qualtity ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '1'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go_version }}
          cache: false

      - name: Test Go Code
        run: go test -v ./...

  building:

    runs-on: ubuntu-latest
    needs: [ code_qualtity, testing ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Fetch tags from Git
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go_version }}
          cache: false

      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: "${{ github.event.repository.name }}-binaries"
          path: |
            ${{ github.event.repository.name }}*
