name: Golang Code Quality

on:
  push:
    paths:
      - '**.go'
      - 'go.mod'
  pull_request:
    types: [opened, reopened]

permissions:
  contents: write

jobs:
  code_qualtity:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'

      - name: Install required packages
        run: |
          sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"

      - name: Install required packages
        run: |
          sudo apt-get install -y make gcc pkg-config libunwind-dev
          
      - name: Install required package
        run: |
          sudo apt-get install -y -f \
            gstreamer1.0-tools \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-plugins-base \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev


      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.58.1"
          install-mode: "goinstall"
          args: '--config=".github/linters/.golangci.yaml" --timeout 60m'
