name: Add PR to Project
on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  add_pr_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: 'https://github.com/orgs/roclub/projects/9'
          github-token: ${{ github.TOKEN }}
