name: release-please

on:
  workflow_call:
    inputs:
      toolchain_version:
        required: false
        type: string
        default: "stable"
    outputs:
      release_upload_url:
        description: "The URL of the releae to upload artifacts to."
        value: ${{ jobs.release_please.outputs.release_upload_url }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release_please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release_please
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `PAT_RELEASEPLEASE` (this secret name is not important).
          token: ${{ secrets.GITHUB_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: simple
    outputs:
      release_upload_url: ${{ steps.replease_please.outputs.upload_url }}
