name: release-please

on:
  workflow_call:
    inputs:
      artifact_name:
        required: false
        type: string
        default: ""

permissions:
  contents: write
  pull-requests: write

jobs:
  release_please:
    runs-on: ubuntu-latest
    steps:

      - name: Download Artifacts
        if: ${{ inputs.artifact_name }} != "" 
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: artifacts/${{ inputs.artifact_name }}/
       
      - name: Create Release
        uses: google-github-actions/release-please-action@v4
        id: release_please
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `PAT_RELEASEPLEASE` (this secret name is not important).
          token: ${{ secrets.GITHUB_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: simple

      - name: Upload Release Artifact
        if: ${{ steps.release_please.outputs.release_created }} && ${{ inputs.artifact_name }} != "" 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./artifact/${{ inputs.artifact_name }}/*
