name: Terraform Code Qualtity

on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read            # git permissions to repo pull/push
  statuses: write           # read/write to repo custom statuses and checks  

jobs:
  code_qualtity:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: latest

      - name: Check for Formatting Errors
        run: terraform fmt -check -recursive

      - name: Check for Linting Errors
        run: |
          tflint --init
          tflint -c ".github/linters/.tflint.hcl" --recursive
