name: Terraform

on:
  workflow_call:
    inputs:
      artifact_name:
        required: false
        type: string
      artifact_target_directory:
        required: false
        type: string
      terraform_version:
        required: true
        type: string
      terraform_directory:
        required: false
        type: string
        default: "."
      terraform_workspace:
        required: false
        type: string
      environment:
        required: true
        type: string
      target:
        required: false
        type: string

env:
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  terraform:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.terraform_directory }}

    steps:
      - name: "Checkout Git repository"
        uses: actions/checkout@v2

      - name: "Download Artifacts"
        if: ${{ inputs.artifact_name != '' }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_target_directory }}

      - name: 'Install Specific Version of AWS CLI'
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.12.6.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Import Secrets from Vault
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.mgt.roclub.io
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            ${{ secrets.ENV }}-aws/deploy accessKey | AWS_ACCESS_KEY_ID ;
            ${{ secrets.ENV }}-aws/deploy secretKey | AWS_SECRET_ACCESS_KEY ;
            github/terraform apiKey | TERRAFORM_CLOUD_AUTH ;
            github/tailscale authKey | TAILSCALE_AUTH_KEY ;


      - name: "Install Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_AUTH }}

      - name: "Select workspace"
        run: |
          mkdir .terraform
          printf '%s' ${{ inputs.terraform_workspace }} > .terraform/environment

      - name: "Validate Terraform"
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.secrets.outputs.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.secrets.outputs.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
          TF_VAR_ENVIRONMENT: ${{ inputs.terraform_workspace }}
          TF_VAR_TAILSCALE_AUTH_KEY: ${{ steps.secrets.outputs.TAILSCALE_AUTH_KEY }}
          TF_VAR_BUBBLE_CALLBACK_KEY: ${{ secrets.BUBBLE_CALLBACK_KEY }}
          TF_VAR_SYSDIG_SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}
          TF_VAR_CONFLUENT_CLOUD_API_KEY: ${{ secrets.TF_VAR_CONFLUENT_CLOUD_API_KEY }}
          TF_VAR_CONFLUENT_CLOUD_API_SECRET: ${{ secrets.TF_VAR_CONFLUENT_CLOUD_API_SECRET }}
          TF_VAR_MONDAY_AUTH: ${{ secrets.MONDAY_AUTH }}
          TF_VAR_POWERFLOW_MAIL_AUTH: ${{ secrets.POWERFLOW_MAIL_AUTH }}
        run: |
          terraform init
          terraform validate -no-color
          terraform fmt -check -recursive

      - name: "Apply Terraform until target"
        if: ${{ inputs.target != '' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.secrets.outputs.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.secrets.outputs.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
          TF_VAR_ENVIRONMENT: ${{ inputs.terraform_workspace }}
          TF_VAR_TAILSCALE_AUTH_KEY: ${{ steps.secrets.outputs.TAILSCALE_AUTH_KEY }}
          TF_VAR_BUBBLE_CALLBACK_KEY: ${{ secrets.BUBBLE_CALLBACK_KEY }}
          TF_VAR_SYSDIG_SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}
          TF_VAR_CONFLUENT_CLOUD_API_KEY: ${{ secrets.TF_VAR_CONFLUENT_CLOUD_API_KEY }}
          TF_VAR_CONFLUENT_CLOUD_API_SECRET: ${{ secrets.TF_VAR_CONFLUENT_CLOUD_API_SECRET }}
          TF_VAR_MONDAY_AUTH: ${{ secrets.MONDAY_AUTH }}
          TF_VAR_POWERFLOW_MAIL_AUTH: ${{ secrets.POWERFLOW_MAIL_AUTH }}
        run: |
          terraform init
          terraform apply -auto-approve -target=${{ inputs.target }}

      - name: "Apply Terraform until end"
        if: ${{ inputs.target == '' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.secrets.outputs.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.secrets.outputs.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
          TF_VAR_ENVIRONMENT: ${{ inputs.terraform_workspace }}
          TF_VAR_TAILSCALE_AUTH_KEY: ${{ steps.secrets.outputs.TAILSCALE_AUTH_KEY }}
          TF_VAR_BUBBLE_CALLBACK_KEY: ${{ secrets.BUBBLE_CALLBACK_KEY }}
          TF_VAR_SYSDIG_SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}
          TF_VAR_CONFLUENT_CLOUD_API_KEY: ${{ secrets.TF_VAR_CONFLUENT_CLOUD_API_KEY }}
          TF_VAR_CONFLUENT_CLOUD_API_SECRET: ${{ secrets.TF_VAR_CONFLUENT_CLOUD_API_SECRET }}
          TF_VAR_MONDAY_AUTH: ${{ secrets.MONDAY_AUTH }}
          TF_VAR_POWERFLOW_MAIL_AUTH: ${{ secrets.POWERFLOW_MAIL_AUTH }}
        run: |
          terraform init
          terraform apply -auto-approve
